### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by Mikle103** [Mikle103/legends-of-the-old-west#3]
@amis92
Hey Amadeusz 
Just a quick question, So if i update my repo and then do a pull request here to the BSData repo it will update the repo after approvel?

In other words from code tab I request a 'New Pull Request' and get 
![image](https://user-images.githubusercontent.com/30399027/36705127-7f4035fc-1bb3-11e8-9375-639ab1d51cc0.png)
then just click 'Create pull request'

Hope this makes sense.

Cheers
Micheal

**Comment by amis92** [comment]
Yeah, that should work. Beware however to update (or even better, rebase) your forked repo after pull requests are merged.

It'd be better if you read some manuals: https://help.github.com/articles/working-with-forks/ :)

**Comment by Mikle103** [comment]
Thanks for the info and your help.
